# Generated by Django 6.0.2 on 2026-02-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scena',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=200)),
                ('scena_arrivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scelte_in_arrivo', to='gameplay.scena')),
                ('scena_partenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scelte', to='gameplay.scena')),
            ],
        ),
    ]
