# Generated by Django 6.0.2 on 2026-02-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scelta',
            old_name='testo',
            new_name='testo_bottone',
        ),
        migrations.RemoveField(
            model_name='scena',
            name='descrizione',
        ),
        migrations.AddField(
            model_name='scena',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='scelta',
            name='scena_arrivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scelte_in_arrivo', to='gameplay.scena'),
        ),
        migrations.CreateModel(
            name='DialogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('character_name', models.CharField(max_length=100)),
                ('character_sprite', models.ImageField(blank=True, null=True, upload_to='sprites/')),
                ('text', models.TextField()),
                ('scena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='gameplay.scena')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
