# Generated by Django 6.0.2 on 2026-02-16 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_rename_testo_scelta_testo_bottone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icona', models.ImageField(blank=True, null=True, upload_to='oggetti/')),
            ],
        ),
        migrations.AddField(
            model_name='scelta',
            name='oggetto_ricevuto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scelte_che_danno', to='gameplay.oggetto'),
        ),
        migrations.AddField(
            model_name='scelta',
            name='oggetto_richiesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scelte_che_richiedono', to='gameplay.oggetto'),
        ),
    ]
