# Generated by Django 6.0.2 on 2026-02-16 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_oggetto_scelta_oggetto_ricevuto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oggetto',
            options={'verbose_name': 'Oggetto', 'verbose_name_plural': 'Oggetti'},
        ),
        migrations.AlterModelOptions(
            name='scelta',
            options={'verbose_name': 'Scelta', 'verbose_name_plural': 'Scelte'},
        ),
        migrations.AlterModelOptions(
            name='scena',
            options={'verbose_name': 'Scena', 'verbose_name_plural': 'Scene'},
        ),
        migrations.CreateModel(
            name='ActionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_bottone', models.CharField(max_length=200)),
                ('oggetto_richiesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_nodes_che_richiedono', to='gameplay.oggetto')),
                ('scena_fallimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_nodes_fallimento', to='gameplay.scena')),
                ('scena_partenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_nodes', to='gameplay.scena')),
                ('scena_successo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_nodes_successo', to='gameplay.scena')),
            ],
            options={
                'verbose_name': 'Action Node',
                'verbose_name_plural': 'Action Nodes',
            },
        ),
    ]
